#!/bin/bash

python main.py \
    --mode train \
    --exper-name final_fix_adamw_baseline_replicate \
    --gpu 0 \
    --epochs 20 \
    --batch-size 8 \
    --optimizer AdamW \
    --lr 0.003 \
    --lr-image-encoder 1e-5 \
    --lr-prompt-learner 0.001 \
    --lr-adapter 0.001 \
    --weight-decay 0.0001 \
    --momentum 0.9 \
    --milestones 10 15 \
    --gamma 0.1 \
    --temporal-layers 1 \
    --num-segments 16 \
    --duration 1 \
    --image-size 224 \
    --seed 42 \
    --print-freq 10 \
    --root-dir /kaggle/input/raer-video-emotion-dataset \
    --train-annotation /kaggle/input/raer-annot/annotation/train.txt \
    --val-annotation /kaggle/input/raer-annot/annotation/test.txt \
    --test-annotation /kaggle/input/raer-annot/annotation/test.txt \
    --clip-path ViT-B/32 \
    --bounding-box-face /kaggle/input/raer-video-emotion-dataset/RAER/bounding_box/face.json \
    --bounding-box-body /kaggle/input/raer-video-emotion-dataset/RAER/bounding_box/body.json \
    --text-type class_descriptor \
    --contexts-number 8 \
    --class-token-position end \
    --class-specific-contexts True \
    --load_and_tune_prompt_learner True \
    --lambda_mi 0 \
    --lambda_dc 0 \
    --mi-warmup 0 \
    --mi-ramp 0 \
    --dc-warmup 0 \
    --dc-ramp 0 \
    --slerp-weight 0.0 \
    --temperature 0.07 \
    --label-smoothing 0 \
    --grad-clip 0.0
