#!/bin/bash

python main.py \
  --mode train \
  --exper-name final_AttnPool_LDL_MoCo_UAR70 \
  --gpu 0 \
  --epochs 60 \
  --batch-size 16 \
  --optimizer AdamW \
  --lr 1e-4 \
  --lr-image-encoder 1e-6 \
  --lr-prompt-learner 5e-4 \
  --lr-adapter 1e-4 \
  --weight-decay 0.0001 \
  --milestones 25 45 \
  --gamma 0.1 \
  --temporal-layers 1 \
  --num-segments 16 \
  --duration 1 \
  --image-size 224 \
  --seed 42 \
  --print-freq 10 \
  --root-dir /kaggle/input/raer-video-emotion-dataset \
  --train-annotation /kaggle/input/raer-annot/annotation/train_80.txt \
  --val-annotation /kaggle/input/raer-annot/annotation/val_20.txt \
  --test-annotation /kaggle/input/raer-annot/annotation/test.txt \
  --clip-path ViT-B/32 \
  --bounding-box-face /kaggle/input/raer-video-emotion-dataset/RAER/bounding_box/face.json \
  --bounding-box-body /kaggle/input/raer-video-emotion-dataset/RAER/bounding_box/body.json \
  --text-type prompt_ensemble \
  --contexts-number 12 \
  --class-token-position end \
  --class-specific-contexts True \
  --load_and_tune_prompt_learner True \
  --lambda_dc 0.1 \
  --dc-warmup 5 \
  --dc-ramp 10 \
  --lambda_mi 0.1 \
  --mi-warmup 10 \
  --mi-ramp 15 \
  --slerp-weight 0.0 \
  --temperature 0.07 \
  --use-ldl \
  --ldl-temperature 1.0 \
  --use-moco \
  --moco-k 4096 \
  --moco-m 0.99 \
  --use-amp \
  --use-weighted-sampler \
  --crop-body \
  --grad-clip 1.0
